// @generated by protoc-gen-connect-es v0.13.2 with parameter "target=ts"
// @generated from file grpc_health.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthCheckRequest, HealthCheckResponse } from "./grpc_health_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service grpc.health.v1.Health
 */
export const Health = {
  typeName: "grpc.health.v1.Health",
  methods: {
    /**
     * @generated from rpc grpc.health.v1.Health.Check
     */
    check: {
      name: "Check",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpc.health.v1.Health.Watch
     */
    watch: {
      name: "Watch",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

