// @generated by protoc-gen-connect-es v0.13.2 with parameter "target=ts"
// @generated from file user.proto (package panels.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, DeleteUserByIdRequest, DeleteUserByNameRequest, GetUserByIdRequest, GetUserByNameRequest, UpdateUserByIdRequest, UpdateUserByNameRequest, User } from "./user_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panels.user.v1.UserService
 */
export const UserService = {
  typeName: "panels.user.v1.UserService",
  methods: {
    /**
     * @generated from rpc panels.user.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserByIdRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.GetUserByName
     */
    getUserByName: {
      name: "GetUserByName",
      I: GetUserByNameRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserByIdRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.UpdateUserByName
     */
    updateUserByName: {
      name: "UpdateUserByName",
      I: UpdateUserByNameRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserByIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panels.user.v1.UserService.DeleteUserByName
     */
    deleteUserByName: {
      name: "DeleteUserByName",
      I: DeleteUserByNameRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

