apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-service
  strategy: {}
  template:
    metadata:
      labels:
        app: panel-service
    spec:
      containers:
      - name: panel-service
        image: panels/panel-service
        ports:
          - containerPort: 9090
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: postgres-host
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: postgres-user
          - name: POSTGRES_PASS
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: postgres-pass
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: postgres-database
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: redis-host
          - name: REDIS_PASS
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: redis-pass
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: panel-service-config
                key: log-level
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: panels-shared-config
                key: kafka-brokers
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: panel-service
spec:
  selectors:
    app: panel-service
  type: ClusterIP
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP